# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

workspace 'AirMapsExplorer.xcworkspace'

target 'AirMapsExplorer' do
  pod 'react-native-maps', path: '../../'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'RCTImage',
  ]

  target 'AirMaps' do
    project '../../ios/AirMaps.xcodeproj'
  end
end

target 'AirMapsExplorerTests' do

end

